[project]
name = "persistent"
version = "0.1.2"
description = "A proof-of-concept persistent chatbot implementation"
readme = "README.markdown"
requires-python = ">=3.13"
dependencies = ["openai", "playwright", "tiktoken"]
