name: Publish Docker Image to GitHub Container Registry

on: push

permissions:
  contents: read
  packages: write

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: GitHub Container Registry login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      # Upper-case repo names fail to build
      - name: Lower-case repo name
        run: echo "REPOSITORY_NAME=$(echo ${GITHUB_REPOSITORY} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.REPOSITORY_NAME }}:latest
          cache-from: type=registry,ref=ghcr.io/${{ env.REPOSITORY_NAME }}:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ env.REPOSITORY_NAME }}:buildcache,mode=max
